### ISSUE TITLE
Add screen Home

### ISSUE THREAD

**Issue by firasrg** [JiggyDevs/twikkl-app#5]
Home screen must be shown as a preview of the device's front or back camera. It must also have some icons as UI buttons.

In order to know the full perspective, please refer to design images available [under /docs](https://github.com/firasrg/twikkl-app/tree/master/docs/design-imgs/home) folder. 

NOTE: currently there is actually a screen `Create Account` (represented by Register.tsx file), and there is no [navigation](https://docs.expo.dev/guides/routing-and-navigation/) yet, so feel free to replace Register screen in App.tsx while you're developing it as follows:
```tsx
export default function App() {
  //.. some code
  else {
    return (
      <PaperProvider theme={theme}>
        <StatusBar style="auto" />
        <ScreenHome /> // 👈 HERE
      </PaperProvider>
    );
  }
}
```

Once done, we're going to add navigation setup between multiple screens.

**Comment by firasrg** [comment]
FYI, there is a new update in README file: Under [**Styling** section](https://github.com/JiggyDevs/twikkl-app#styling), we added a link to our design assets to provide you with the full picture of the app.

**Comment by JiggyTheGrey** [comment]
The home screen must showcase various video content from creators (like TikTok), along with intuitive UI icons serving as buttons for seamless user interaction.

**Comment by firasrg** [comment]
@JiggyTheGrey yes I'm aware of that

**Comment by firasrg** [comment]
The issue continues as it's waiting for the home screen to be done! 😄

**Comment by Vcky4** [comment]
I've done some resizing with other functions

**Comment by Vcky4** [comment]
> The home screen must showcase various video content from creators (like TikTok), along with intuitive UI icons serving as buttons for seamless user interaction.

done though same content for now

**Comment by firasrg** [comment]
@Vcky4 Please take into account my review comments in PR #19 . thanks
