### ISSUE TITLE
Set up navigation and routing

### ISSUE THREAD

**Issue by firasrg** [JiggyDevs/twikkl-app#8]
Hello! 

In the context of app-scaling, its obvious to have multiple screens and user(s) will want to navigate through. Thus, we expect to use [react-navigation](https://reactnavigation.org/) in combination with [expo-router](https://docs.expo.dev/guides/routing-and-navigation/).

**Comment by kaushikc44** [comment]
Hi I can help you with Routing can you please specify how exactly are you looking to navigate and route ?

**Comment by firasrg** [comment]
Hello @kaushikc44 ! Thats good initiative, I appreciate you're interested. Actually, there is only **one** screen available [Create Account / Register](https://github.com/firasrg/twikkl-app/blob/master/docs/demo/demo-1.gif), so it might be early. 

Otherwise, we can have the setup even with one screen. Feel free to send your pull request.

**Comment by firasrg** [comment]
FYI, I take up this issue.
